#JavaScript错误处理机制

####Error对象

#####基本属性
+ `name`：错误名称
+ `message`：错误提示信息
+ `stack`：错误的堆栈（非标准属性，但是大多数平台支持）

#####原生错误类型

1. `SyntaxError`：解析代码错误，写错了
2. `ReferenceError`：引用错误，引用了一个不存在的变量或或者对一个不允许改变的变量赋值（例：函数允许结果或this赋值）
3. `RangeError`：值超过有效范围错误，数组下标负值等
4. `TypeError`：类型错误
5. `URIError`：URIError是URI相关函数的参数不正确时抛出的错误，主要涉及encodeURI()、decodeURI()、encodeURIComponent()、decodeURIComponent()、escape()和unescape()这六个函数
6. `EvalError`：eval函数没有被正确执行时，会抛出EvalError错误

#####自定义错误

```
function UserError(message) {
   this.message = message || "默认信息";
   this.name = "UserError";
}

UserError.prototype = new Error();
UserError.prototype.constructor = UserError;

new UserError("这是自定义的错误！");
```


#####throw

throw可以接受各种值作为参数。JavaScript引擎一旦遇到throw语句，就会停止执行后面的语句，并将throw语句的参数值，返回给用户

```
function UserError(message) {
  this.message = message || "默认信息";
  this.name = "UserError";
}

UserError.prototype.toString = function (){
  return this.name + ': "' + this.message + '"';
}

throw new UserError("出错了！");
```

#####try...catch...finally

```
function f() {
  try {
    console.log(0);
    throw "bug";
  } catch(e) {
    console.log(1);
    return true; // 这句原本会延迟到finally代码块结束再执行
    console.log(2); // 不会运行
  } finally {
    console.log(3);
    return false; // 这句会覆盖掉前面那句return
    console.log(4); // 不会运行
  }

  console.log(5); // 不会运行
}
```